apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: property-api
  template:
    metadata:
      labels:
        app: property-api
    spec:
      containers:
      - name: property-api
        image: property-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
